apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-namenode
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-namenode
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-namenode
    spec:
      containers:
        - name: namenode
          image: {{ .Values.namenode.image.repository }}:{{ .Values.namenode.image.tag }}
          ports:
            - containerPort: 9870
            - containerPort: 8020
            - containerPort: 9000
          env:
            - name: CLUSTER_NAME
              value: {{ .Values.namenode.clusterName }}
        {{- range $key, $value := .Values.hadoopEnvVars }}
            - name: {{ $key }}
              value: {{ $value | quote }}
        {{- end }}
          volumeMounts:
            - name: hadoop-config
              mountPath: /opt/hadoop-3.2.1/etc/hadoop
            - name: namenode-data
              mountPath: /hadoop/dfs/name
      volumes:
        - name: hadoop-config
          configMap:
            name: {{ .Release.Name }}-hadoop-config
        - name: namenode-data
        {{- if .Values.namenode.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-namenode-pvc
        {{- else }}
          emptyDir: {}
        {{- end }}