spark.sql.defaultCatalog hadoop_prod
spark.sql.catalog.hadoop_prod type=hadoop
spark.sql.catalog.hadoop_prod.catalog-impl org.apache.iceberg.hadoop.HadoopCatalog
spark.sql.catalog.hadoop_prod.warehouse hdfs://hadoop-hadoop-hdfs-nn:9000/warehouse
spark.sql.extensions org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
