// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/protobuf/message.proto

package org.example.proto;

public final class Message {
  private Message() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface EventDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.example.proto.EventData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string event_date = 1;</code>
     * @return The eventDate.
     */
    java.lang.String getEventDate();
    /**
     * <code>string event_date = 1;</code>
     * @return The bytes for eventDate.
     */
    com.google.protobuf.ByteString
        getEventDateBytes();

    /**
     * <code>string event_time = 2;</code>
     * @return The eventTime.
     */
    java.lang.String getEventTime();
    /**
     * <code>string event_time = 2;</code>
     * @return The bytes for eventTime.
     */
    com.google.protobuf.ByteString
        getEventTimeBytes();

    /**
     * <code>string event_type = 3;</code>
     * @return The eventType.
     */
    java.lang.String getEventType();
    /**
     * <code>string event_type = 3;</code>
     * @return The bytes for eventType.
     */
    com.google.protobuf.ByteString
        getEventTypeBytes();

    /**
     * <code>int64 product_id = 4;</code>
     * @return The productId.
     */
    long getProductId();

    /**
     * <code>int64 category_id = 5;</code>
     * @return The categoryId.
     */
    long getCategoryId();

    /**
     * <code>string category_code = 6;</code>
     * @return The categoryCode.
     */
    java.lang.String getCategoryCode();
    /**
     * <code>string category_code = 6;</code>
     * @return The bytes for categoryCode.
     */
    com.google.protobuf.ByteString
        getCategoryCodeBytes();

    /**
     * <code>string brand = 7;</code>
     * @return The brand.
     */
    java.lang.String getBrand();
    /**
     * <code>string brand = 7;</code>
     * @return The bytes for brand.
     */
    com.google.protobuf.ByteString
        getBrandBytes();

    /**
     * <code>float price = 8;</code>
     * @return The price.
     */
    float getPrice();

    /**
     * <code>int64 user_id = 9;</code>
     * @return The userId.
     */
    long getUserId();

    /**
     * <code>string user_session = 10;</code>
     * @return The userSession.
     */
    java.lang.String getUserSession();
    /**
     * <code>string user_session = 10;</code>
     * @return The bytes for userSession.
     */
    com.google.protobuf.ByteString
        getUserSessionBytes();
  }
  /**
   * Protobuf type {@code org.example.proto.EventData}
   */
  public static final class EventData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.example.proto.EventData)
      EventDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EventData.newBuilder() to construct.
    private EventData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EventData() {
      eventDate_ = "";
      eventTime_ = "";
      eventType_ = "";
      categoryCode_ = "";
      brand_ = "";
      userSession_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new EventData();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EventData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              eventDate_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              eventTime_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              eventType_ = s;
              break;
            }
            case 32: {

              productId_ = input.readInt64();
              break;
            }
            case 40: {

              categoryId_ = input.readInt64();
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              categoryCode_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              brand_ = s;
              break;
            }
            case 69: {

              price_ = input.readFloat();
              break;
            }
            case 72: {

              userId_ = input.readInt64();
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              userSession_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.proto.Message.internal_static_org_example_proto_EventData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.proto.Message.internal_static_org_example_proto_EventData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.proto.Message.EventData.class, org.example.proto.Message.EventData.Builder.class);
    }

    public static final int EVENT_DATE_FIELD_NUMBER = 1;
    private volatile java.lang.Object eventDate_;
    /**
     * <code>string event_date = 1;</code>
     * @return The eventDate.
     */
    @java.lang.Override
    public java.lang.String getEventDate() {
      java.lang.Object ref = eventDate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventDate_ = s;
        return s;
      }
    }
    /**
     * <code>string event_date = 1;</code>
     * @return The bytes for eventDate.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEventDateBytes() {
      java.lang.Object ref = eventDate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EVENT_TIME_FIELD_NUMBER = 2;
    private volatile java.lang.Object eventTime_;
    /**
     * <code>string event_time = 2;</code>
     * @return The eventTime.
     */
    @java.lang.Override
    public java.lang.String getEventTime() {
      java.lang.Object ref = eventTime_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventTime_ = s;
        return s;
      }
    }
    /**
     * <code>string event_time = 2;</code>
     * @return The bytes for eventTime.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEventTimeBytes() {
      java.lang.Object ref = eventTime_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EVENT_TYPE_FIELD_NUMBER = 3;
    private volatile java.lang.Object eventType_;
    /**
     * <code>string event_type = 3;</code>
     * @return The eventType.
     */
    @java.lang.Override
    public java.lang.String getEventType() {
      java.lang.Object ref = eventType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventType_ = s;
        return s;
      }
    }
    /**
     * <code>string event_type = 3;</code>
     * @return The bytes for eventType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEventTypeBytes() {
      java.lang.Object ref = eventType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRODUCT_ID_FIELD_NUMBER = 4;
    private long productId_;
    /**
     * <code>int64 product_id = 4;</code>
     * @return The productId.
     */
    @java.lang.Override
    public long getProductId() {
      return productId_;
    }

    public static final int CATEGORY_ID_FIELD_NUMBER = 5;
    private long categoryId_;
    /**
     * <code>int64 category_id = 5;</code>
     * @return The categoryId.
     */
    @java.lang.Override
    public long getCategoryId() {
      return categoryId_;
    }

    public static final int CATEGORY_CODE_FIELD_NUMBER = 6;
    private volatile java.lang.Object categoryCode_;
    /**
     * <code>string category_code = 6;</code>
     * @return The categoryCode.
     */
    @java.lang.Override
    public java.lang.String getCategoryCode() {
      java.lang.Object ref = categoryCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        categoryCode_ = s;
        return s;
      }
    }
    /**
     * <code>string category_code = 6;</code>
     * @return The bytes for categoryCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCategoryCodeBytes() {
      java.lang.Object ref = categoryCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        categoryCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BRAND_FIELD_NUMBER = 7;
    private volatile java.lang.Object brand_;
    /**
     * <code>string brand = 7;</code>
     * @return The brand.
     */
    @java.lang.Override
    public java.lang.String getBrand() {
      java.lang.Object ref = brand_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        brand_ = s;
        return s;
      }
    }
    /**
     * <code>string brand = 7;</code>
     * @return The bytes for brand.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBrandBytes() {
      java.lang.Object ref = brand_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        brand_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRICE_FIELD_NUMBER = 8;
    private float price_;
    /**
     * <code>float price = 8;</code>
     * @return The price.
     */
    @java.lang.Override
    public float getPrice() {
      return price_;
    }

    public static final int USER_ID_FIELD_NUMBER = 9;
    private long userId_;
    /**
     * <code>int64 user_id = 9;</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }

    public static final int USER_SESSION_FIELD_NUMBER = 10;
    private volatile java.lang.Object userSession_;
    /**
     * <code>string user_session = 10;</code>
     * @return The userSession.
     */
    @java.lang.Override
    public java.lang.String getUserSession() {
      java.lang.Object ref = userSession_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userSession_ = s;
        return s;
      }
    }
    /**
     * <code>string user_session = 10;</code>
     * @return The bytes for userSession.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserSessionBytes() {
      java.lang.Object ref = userSession_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userSession_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getEventDateBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, eventDate_);
      }
      if (!getEventTimeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, eventTime_);
      }
      if (!getEventTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, eventType_);
      }
      if (productId_ != 0L) {
        output.writeInt64(4, productId_);
      }
      if (categoryId_ != 0L) {
        output.writeInt64(5, categoryId_);
      }
      if (!getCategoryCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, categoryCode_);
      }
      if (!getBrandBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, brand_);
      }
      if (java.lang.Float.floatToRawIntBits(price_) != 0) {
        output.writeFloat(8, price_);
      }
      if (userId_ != 0L) {
        output.writeInt64(9, userId_);
      }
      if (!getUserSessionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, userSession_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getEventDateBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, eventDate_);
      }
      if (!getEventTimeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, eventTime_);
      }
      if (!getEventTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, eventType_);
      }
      if (productId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, productId_);
      }
      if (categoryId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, categoryId_);
      }
      if (!getCategoryCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, categoryCode_);
      }
      if (!getBrandBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, brand_);
      }
      if (java.lang.Float.floatToRawIntBits(price_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(8, price_);
      }
      if (userId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, userId_);
      }
      if (!getUserSessionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, userSession_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.example.proto.Message.EventData)) {
        return super.equals(obj);
      }
      org.example.proto.Message.EventData other = (org.example.proto.Message.EventData) obj;

      if (!getEventDate()
          .equals(other.getEventDate())) return false;
      if (!getEventTime()
          .equals(other.getEventTime())) return false;
      if (!getEventType()
          .equals(other.getEventType())) return false;
      if (getProductId()
          != other.getProductId()) return false;
      if (getCategoryId()
          != other.getCategoryId()) return false;
      if (!getCategoryCode()
          .equals(other.getCategoryCode())) return false;
      if (!getBrand()
          .equals(other.getBrand())) return false;
      if (java.lang.Float.floatToIntBits(getPrice())
          != java.lang.Float.floatToIntBits(
              other.getPrice())) return false;
      if (getUserId()
          != other.getUserId()) return false;
      if (!getUserSession()
          .equals(other.getUserSession())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EVENT_DATE_FIELD_NUMBER;
      hash = (53 * hash) + getEventDate().hashCode();
      hash = (37 * hash) + EVENT_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getEventTime().hashCode();
      hash = (37 * hash) + EVENT_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getEventType().hashCode();
      hash = (37 * hash) + PRODUCT_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getProductId());
      hash = (37 * hash) + CATEGORY_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCategoryId());
      hash = (37 * hash) + CATEGORY_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCategoryCode().hashCode();
      hash = (37 * hash) + BRAND_FIELD_NUMBER;
      hash = (53 * hash) + getBrand().hashCode();
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getPrice());
      hash = (37 * hash) + USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUserId());
      hash = (37 * hash) + USER_SESSION_FIELD_NUMBER;
      hash = (53 * hash) + getUserSession().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.example.proto.Message.EventData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.proto.Message.EventData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.proto.Message.EventData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.proto.Message.EventData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.proto.Message.EventData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.proto.Message.EventData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.proto.Message.EventData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.proto.Message.EventData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.proto.Message.EventData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.example.proto.Message.EventData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.proto.Message.EventData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.proto.Message.EventData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.example.proto.Message.EventData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.example.proto.EventData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.example.proto.EventData)
        org.example.proto.Message.EventDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.proto.Message.internal_static_org_example_proto_EventData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.proto.Message.internal_static_org_example_proto_EventData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.proto.Message.EventData.class, org.example.proto.Message.EventData.Builder.class);
      }

      // Construct using org.example.proto.Message.EventData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        eventDate_ = "";

        eventTime_ = "";

        eventType_ = "";

        productId_ = 0L;

        categoryId_ = 0L;

        categoryCode_ = "";

        brand_ = "";

        price_ = 0F;

        userId_ = 0L;

        userSession_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.example.proto.Message.internal_static_org_example_proto_EventData_descriptor;
      }

      @java.lang.Override
      public org.example.proto.Message.EventData getDefaultInstanceForType() {
        return org.example.proto.Message.EventData.getDefaultInstance();
      }

      @java.lang.Override
      public org.example.proto.Message.EventData build() {
        org.example.proto.Message.EventData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.example.proto.Message.EventData buildPartial() {
        org.example.proto.Message.EventData result = new org.example.proto.Message.EventData(this);
        result.eventDate_ = eventDate_;
        result.eventTime_ = eventTime_;
        result.eventType_ = eventType_;
        result.productId_ = productId_;
        result.categoryId_ = categoryId_;
        result.categoryCode_ = categoryCode_;
        result.brand_ = brand_;
        result.price_ = price_;
        result.userId_ = userId_;
        result.userSession_ = userSession_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.example.proto.Message.EventData) {
          return mergeFrom((org.example.proto.Message.EventData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.example.proto.Message.EventData other) {
        if (other == org.example.proto.Message.EventData.getDefaultInstance()) return this;
        if (!other.getEventDate().isEmpty()) {
          eventDate_ = other.eventDate_;
          onChanged();
        }
        if (!other.getEventTime().isEmpty()) {
          eventTime_ = other.eventTime_;
          onChanged();
        }
        if (!other.getEventType().isEmpty()) {
          eventType_ = other.eventType_;
          onChanged();
        }
        if (other.getProductId() != 0L) {
          setProductId(other.getProductId());
        }
        if (other.getCategoryId() != 0L) {
          setCategoryId(other.getCategoryId());
        }
        if (!other.getCategoryCode().isEmpty()) {
          categoryCode_ = other.categoryCode_;
          onChanged();
        }
        if (!other.getBrand().isEmpty()) {
          brand_ = other.brand_;
          onChanged();
        }
        if (other.getPrice() != 0F) {
          setPrice(other.getPrice());
        }
        if (other.getUserId() != 0L) {
          setUserId(other.getUserId());
        }
        if (!other.getUserSession().isEmpty()) {
          userSession_ = other.userSession_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.example.proto.Message.EventData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.example.proto.Message.EventData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object eventDate_ = "";
      /**
       * <code>string event_date = 1;</code>
       * @return The eventDate.
       */
      public java.lang.String getEventDate() {
        java.lang.Object ref = eventDate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          eventDate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string event_date = 1;</code>
       * @return The bytes for eventDate.
       */
      public com.google.protobuf.ByteString
          getEventDateBytes() {
        java.lang.Object ref = eventDate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          eventDate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string event_date = 1;</code>
       * @param value The eventDate to set.
       * @return This builder for chaining.
       */
      public Builder setEventDate(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        eventDate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string event_date = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEventDate() {
        
        eventDate_ = getDefaultInstance().getEventDate();
        onChanged();
        return this;
      }
      /**
       * <code>string event_date = 1;</code>
       * @param value The bytes for eventDate to set.
       * @return This builder for chaining.
       */
      public Builder setEventDateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        eventDate_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object eventTime_ = "";
      /**
       * <code>string event_time = 2;</code>
       * @return The eventTime.
       */
      public java.lang.String getEventTime() {
        java.lang.Object ref = eventTime_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          eventTime_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string event_time = 2;</code>
       * @return The bytes for eventTime.
       */
      public com.google.protobuf.ByteString
          getEventTimeBytes() {
        java.lang.Object ref = eventTime_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          eventTime_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string event_time = 2;</code>
       * @param value The eventTime to set.
       * @return This builder for chaining.
       */
      public Builder setEventTime(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        eventTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string event_time = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearEventTime() {
        
        eventTime_ = getDefaultInstance().getEventTime();
        onChanged();
        return this;
      }
      /**
       * <code>string event_time = 2;</code>
       * @param value The bytes for eventTime to set.
       * @return This builder for chaining.
       */
      public Builder setEventTimeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        eventTime_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object eventType_ = "";
      /**
       * <code>string event_type = 3;</code>
       * @return The eventType.
       */
      public java.lang.String getEventType() {
        java.lang.Object ref = eventType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          eventType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string event_type = 3;</code>
       * @return The bytes for eventType.
       */
      public com.google.protobuf.ByteString
          getEventTypeBytes() {
        java.lang.Object ref = eventType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          eventType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string event_type = 3;</code>
       * @param value The eventType to set.
       * @return This builder for chaining.
       */
      public Builder setEventType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        eventType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string event_type = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEventType() {
        
        eventType_ = getDefaultInstance().getEventType();
        onChanged();
        return this;
      }
      /**
       * <code>string event_type = 3;</code>
       * @param value The bytes for eventType to set.
       * @return This builder for chaining.
       */
      public Builder setEventTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        eventType_ = value;
        onChanged();
        return this;
      }

      private long productId_ ;
      /**
       * <code>int64 product_id = 4;</code>
       * @return The productId.
       */
      @java.lang.Override
      public long getProductId() {
        return productId_;
      }
      /**
       * <code>int64 product_id = 4;</code>
       * @param value The productId to set.
       * @return This builder for chaining.
       */
      public Builder setProductId(long value) {
        
        productId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 product_id = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearProductId() {
        
        productId_ = 0L;
        onChanged();
        return this;
      }

      private long categoryId_ ;
      /**
       * <code>int64 category_id = 5;</code>
       * @return The categoryId.
       */
      @java.lang.Override
      public long getCategoryId() {
        return categoryId_;
      }
      /**
       * <code>int64 category_id = 5;</code>
       * @param value The categoryId to set.
       * @return This builder for chaining.
       */
      public Builder setCategoryId(long value) {
        
        categoryId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 category_id = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCategoryId() {
        
        categoryId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object categoryCode_ = "";
      /**
       * <code>string category_code = 6;</code>
       * @return The categoryCode.
       */
      public java.lang.String getCategoryCode() {
        java.lang.Object ref = categoryCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          categoryCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string category_code = 6;</code>
       * @return The bytes for categoryCode.
       */
      public com.google.protobuf.ByteString
          getCategoryCodeBytes() {
        java.lang.Object ref = categoryCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          categoryCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string category_code = 6;</code>
       * @param value The categoryCode to set.
       * @return This builder for chaining.
       */
      public Builder setCategoryCode(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        categoryCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string category_code = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearCategoryCode() {
        
        categoryCode_ = getDefaultInstance().getCategoryCode();
        onChanged();
        return this;
      }
      /**
       * <code>string category_code = 6;</code>
       * @param value The bytes for categoryCode to set.
       * @return This builder for chaining.
       */
      public Builder setCategoryCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        categoryCode_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object brand_ = "";
      /**
       * <code>string brand = 7;</code>
       * @return The brand.
       */
      public java.lang.String getBrand() {
        java.lang.Object ref = brand_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          brand_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string brand = 7;</code>
       * @return The bytes for brand.
       */
      public com.google.protobuf.ByteString
          getBrandBytes() {
        java.lang.Object ref = brand_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          brand_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string brand = 7;</code>
       * @param value The brand to set.
       * @return This builder for chaining.
       */
      public Builder setBrand(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        brand_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string brand = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearBrand() {
        
        brand_ = getDefaultInstance().getBrand();
        onChanged();
        return this;
      }
      /**
       * <code>string brand = 7;</code>
       * @param value The bytes for brand to set.
       * @return This builder for chaining.
       */
      public Builder setBrandBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        brand_ = value;
        onChanged();
        return this;
      }

      private float price_ ;
      /**
       * <code>float price = 8;</code>
       * @return The price.
       */
      @java.lang.Override
      public float getPrice() {
        return price_;
      }
      /**
       * <code>float price = 8;</code>
       * @param value The price to set.
       * @return This builder for chaining.
       */
      public Builder setPrice(float value) {
        
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float price = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearPrice() {
        
        price_ = 0F;
        onChanged();
        return this;
      }

      private long userId_ ;
      /**
       * <code>int64 user_id = 9;</code>
       * @return The userId.
       */
      @java.lang.Override
      public long getUserId() {
        return userId_;
      }
      /**
       * <code>int64 user_id = 9;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(long value) {
        
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 user_id = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        
        userId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object userSession_ = "";
      /**
       * <code>string user_session = 10;</code>
       * @return The userSession.
       */
      public java.lang.String getUserSession() {
        java.lang.Object ref = userSession_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userSession_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string user_session = 10;</code>
       * @return The bytes for userSession.
       */
      public com.google.protobuf.ByteString
          getUserSessionBytes() {
        java.lang.Object ref = userSession_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userSession_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string user_session = 10;</code>
       * @param value The userSession to set.
       * @return This builder for chaining.
       */
      public Builder setUserSession(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userSession_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string user_session = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserSession() {
        
        userSession_ = getDefaultInstance().getUserSession();
        onChanged();
        return this;
      }
      /**
       * <code>string user_session = 10;</code>
       * @param value The bytes for userSession to set.
       * @return This builder for chaining.
       */
      public Builder setUserSessionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userSession_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.example.proto.EventData)
    }

    // @@protoc_insertion_point(class_scope:org.example.proto.EventData)
    private static final org.example.proto.Message.EventData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.example.proto.Message.EventData();
    }

    public static org.example.proto.Message.EventData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EventData>
        PARSER = new com.google.protobuf.AbstractParser<EventData>() {
      @java.lang.Override
      public EventData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EventData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EventData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EventData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.example.proto.Message.EventData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_example_proto_EventData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_example_proto_EventData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$src/main/java/protobuf/message.proto\022\021" +
      "org.example.proto\"\314\001\n\tEventData\022\022\n\nevent" +
      "_date\030\001 \001(\t\022\022\n\nevent_time\030\002 \001(\t\022\022\n\nevent" +
      "_type\030\003 \001(\t\022\022\n\nproduct_id\030\004 \001(\003\022\023\n\013categ" +
      "ory_id\030\005 \001(\003\022\025\n\rcategory_code\030\006 \001(\t\022\r\n\005b" +
      "rand\030\007 \001(\t\022\r\n\005price\030\010 \001(\002\022\017\n\007user_id\030\t \001" +
      "(\003\022\024\n\014user_session\030\n \001(\tb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_org_example_proto_EventData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_example_proto_EventData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_example_proto_EventData_descriptor,
        new java.lang.String[] { "EventDate", "EventTime", "EventType", "ProductId", "CategoryId", "CategoryCode", "Brand", "Price", "UserId", "UserSession", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
