apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
  labels:
    app: kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
        - name: kafka-producer
          image: lmphuc3012/python-kafka-producer  # Use your image name
          ports:
            - containerPort: 8085
          env:
            - name: KAFKA_BROKER
              value: "kafka-broker-0.kafka-headless.hadoop-cluster:9092,kafka-broker-1.kafka-headless.hadoop-cluster:9092,kafka-broker-2.kafka-headless.hadoop-cluster:9092"
